-- PRAGMA foreign_keys=OFF;
-- BEGIN TRANSACTION;
-- CREATE TABLE IF NOT EXISTS "Syouhin" (
-- [ID] TEXT NOT NULL UNIQUE
-- [Parts] TEXT
-- [Name] TEXT NOT NULL
-- [Version] TEXT
-- [Value] REAL
-- [seinou] REAL NOT NULL
-- [hosei] REAL NOT NULL
-- [Reality] TEXT
-- );